### ISSUE TITLE
Database::connect() does not provide all configured databases

### ISSUE THREAD

**Issue by patrickvuarnoz** [leafsphp/mvc-core#9]
I'm in a project where I need to have multiple MySQL database connections. My setup in the **database config** looks like this:

```
return [
    'default' => _env('DB_CONNECTION', 'mysql_db_1'),
    'connections' => [
        
        'mysql_db_1' => [
            'driver' => 'mysql',
            'url' => _env('DATABASE_URL'),
            'host' => _env('DB_HOST', '127.0.0.1'),
            'port' => _env('DB_PORT', '3306'),
            'database' => _env('DB_DATABASE_1', 'forge'),
            'username' => _env('DB_USERNAME', 'forge'),
            'password' => _env('DB_PASSWORD', ''),
            'unix_socket' => _env('DB_SOCKET', ''),
            'charset' => _env('DB_CHARSET', 'utf8mb4'),
            'collation' => _env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => _env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        
        'mysql_db_2' => [
            'driver' => 'mysql',
            'url' => _env('DATABASE_URL'),
            'host' => _env('DB_HOST', '127.0.0.1'),
            'port' => _env('DB_PORT', '3306'),
            'database' => _env('DB_DATABASE_2', 'forge'),
            'username' => _env('DB_USERNAME', 'forge'),
            'password' => _env('DB_PASSWORD', ''),
            'unix_socket' => _env('DB_SOCKET', ''),
            'charset' => _env('DB_CHARSET', 'utf8mb4'),
            'collation' => _env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => _env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
    ],
];
```

Now I have a model where I tell the model that the database connection it should use is `mysql_db_2`:

```
<?php

namespace App\Models;

class User extends Model
{
    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'mysql_db_2';
}
```

When I run this I get an error from `/leaf/vendor/illuminate/database/DatabaseManager.php` saying that `Database connection [mysql_db_2] not configured.`. I found out that in `/leaf/vendor/leafs/mvc-core/src/Model.php` there is a call to `Database::connect()` which seems to be intended to connect to the databases as soon as `Model.php` is loaded so that the database connections are ready. In `/leaf/vendor/leafs/mvc-core/src/Database.php` the `connect()` method looks like this:

```
    public static function connect()
    {
        $connection = static::$config['default'] ?? 'mysql';

        static::$capsule = new Manager;
        static::$capsule->addConnection(
            static::$config['connections'][$connection]
        );

        static::$capsule->setEventDispatcher(new Dispatcher(new Container));
        static::$capsule->setAsGlobal();
        static::$capsule->bootEloquent();

        if (php_sapi_name() === 'cli') {
            Schema::$capsule = static::$capsule;
        }
    }
```

This will only connect the default database but no other database and it will not provide the default connection under its original name, so this name cannot be used in the models for the `$connection` setting. I have the impression that this method should be extended to initialize all database connections and provide them for the models. The following code would do that and seems to work, but I'm not that deep into Leaf 3 to be able to say whether this has side effects:

```
    public static function connect()
    {        
        static::$capsule = new Manager;
        
        // Add all connections by their name
        foreach (static::$config['connections'] as $name => $config) {
            static::$capsule->addConnection($config, $name);
        }
        
        // Add the default connection for models that don't have an explicit connection set
        static::$capsule->addConnection(static::$config['connections'][static::$config['default']], 'default');
        
        static::$capsule->setEventDispatcher(new Dispatcher(new Container));
        static::$capsule->setAsGlobal();
        static::$capsule->bootEloquent();

        if (php_sapi_name() === 'cli') {
            Schema::$capsule = static::$capsule;
        }
    }
```

I'm using a fresh installation of Leaf in version 3.3.

**Comment by mychidarko** [comment]
This is right @patrickvuarnoz. The implementation only initializes the default connection. This was the intended behaviour at the time, but this will be updated in a later version

**Comment by mychidarko** [comment]
A fix for this is ready, just testing to make sure it does not break any other thing

**Comment by mychidarko** [comment]
Updating leafs/mvc-core and leafs/leaf should fix this issue now

**Comment by patrickvuarnoz** [comment]
@mychidarko Thanks a lot. This also works now with the latest update.

**Comment by patrickvuarnoz** [comment]
@mychidarko I stumbled again over this issue here. The problem I'm facing is that I have two database connections defined, one as `system` and one (let's say) `content`. For some cross-database relations I need to specify the connection name at both models. If I use `system` and `content` on those models it leads to an error:

```
InvalidArgumentException: Database connection [content] not configured.
```

The problem is still the same spot as before in `Database::connect()`: 
```
foreach ($connections as $name => $connection) {
  static::$capsule->addConnection(
    $connection,
    $config['default'] === $name ? 'default' : $name,
  );
}
```
 

The database connection that is defined to be the default connection is not added under its own name but only under the name `default`. This is a bit confusing if you work with named connections. I am aware that there needs to be a connection with the name `default` which will be used for all models that don't explicitly set their own connection name. And I'm also aware that I could name one of my connections `default` and then it would work as well.
 
Still, would it be possible to also create the connection under it's original name? Something like this:

```
foreach ($connections as $name => $connection) {
  static::$capsule->addConnection($connection, $name);
  if ($config['default'] === $name) {
    static::$capsule->addConnection($connection, 'default');
  }
}
```
